name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Generate Allure Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload Allure Report Data
        if: always()  # Ensure this runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Download Allure Report Data from Previous Runs
        uses: actions/download-artifact@v3
        with:
          name: allure-results

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Push Allure Report to `gh-pages` branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check out the `gh-pages` branch
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages

          # Copy the Allure report to the `gh-pages` branch
          cp -R ../allure-report/* .

          # Commit and push the report to the `gh-pages` branch
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages

      - name: Set up GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report

      - name: Update GitHub Pages URL in Repo Description
        uses: octokit/request-action@v2
        with:
          route: PATCH /repos/${{ github.repository }}
          repo: ${{ github.repository }}
          description: 'Allure Report: https://your-username.github.io/your-repo/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
